version: '3.8'

services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-development}
    image: manthan-backend:${TAG:-latest}
    container_name: manthan-backend
    init: true
    ports:
      - "${PORT:-3000}:3000"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./ssl:/usr/src/app/ssl:ro
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - ENABLE_CLUSTERING=${ENABLE_CLUSTERING:-false}
      - CLUSTER_WORKERS=${CLUSTER_WORKERS:-2}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - manthan-network
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: manthan-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - manthan-network

  grafana:
    image: grafana/grafana:latest
    container_name: manthan-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    networks:
      - manthan-network

  redis:
    image: redis:alpine
    container_name: manthan-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - manthan-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - manthan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  manthan-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  redis_data:
  postgres_data: 