groups:
  - name: application_alerts
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High HTTP error rate
          description: "Error rate is {{ $value }} per second for the last 5 minutes"

      # Database Connection Issues
      - alert: DatabaseConnectionIssues
        expr: postgresql_pool_metrics{type="active"} < 1 or mongodb_connection_metrics{state="connected"} != 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Database connection issues detected
          description: "Database connection metrics indicate connectivity problems"

      # High Response Time
      - alert: HighResponseTime
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High response time detected
          description: "Average response time is above 500ms"

      # Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Memory usage is above 85%" 